name: App build

on: push

jobs:
  build_with_signing:
    runs-on: macos-12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          DISTRIBUTION_CERTIFICATE_BASE64: ${{ secrets.DISTRIBUTION_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          DISTRIBUTION_PROFILE_BASE64: ${{ secrets.DISTRIBUTION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          DISTRIBUTION_CERTIFICATE_PATH=$RUNNER_TEMP/distribution_certificate.p12
          
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          DIST_PROFILE_PATH=$RUNNER_TEMP/moviesapp_profile.mobileprovision
          
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          
          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$DISTRIBUTION_CERTIFICATE_BASE64" | base64 --decode --output $DISTRIBUTION_CERTIFICATE_PATH
          
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH
          echo -n "$DISTRIBUTION_PROFILE_BASE64" | base64 --decode --output $DIST_PROFILE_PATH
          
          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          
          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security import $DISTRIBUTION_CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
          
          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
          cp $DIST_PROFILE_PATH ~/Library/MobileDevice/Provisioning\ Profiles
          
      - name: Build iOS APP for Release Production
        run: |
          
          xcodebuild -scheme "movies" \
                    clean archive \
                    -archivePath "Actions" \
                    -configuration "Release" \
                    -clonedSourcePackagesDirPath "SourcePackages"
                    
      - name: Export IPA
        env:
          EXPORT_PLIST: ${{ secrets.EXPORT_PLIST }}
        run: |
          EXPORT_PLIST_PATH=$RUNNER_TEMP/ExportOptions.plist
          echo -n "$EXPORT_PLIST" | base64 --decode --output $EXPORT_PLIST_PATH
          xcodebuild -exportArchive \
                    -archivePath $GITHUB_WORKSPACE/Actions.xcarchive \
                    -exportOptionsPlist $EXPORT_PLIST_PATH \
                    -exportPath $RUNNER_TEMP/export \
                    -allowProvisioningUpdates
          
          cd $RUNNER_TEMP/export
          pwd
      
      - name: Upload IPA
        uses: actions/upload-artifact@master
        with:
          path: /Users/runner/work/_temp/export/
          
      - name: Decode auth, api key file and save it
        env:
          API_KEY_BASE64: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
        run: | 
          mkdir -p ~/private_keys
          ls ~/private_keys
          echo -n "$API_KEY_BASE64" | base64 --decode --output ~/private_keys/AuthKey_${{ secrets.APPSTORE_API_KEY_ID }}.p8
          echo "After saving: "
          ls ~/private_keys
      
      - name: Upload file to testFlight
        run: |
          echo "Start upload"
          ls ~/private_keys
          xcrun altool --validate-app -f $RUNNER_TEMP/export/movies.ipa \
                -t ios \
                --apiKey ${{ secrets.APPSTORE_API_KEY_ID }} \
                --apiIssuer ${{ secrets.APPSTORE_ISSUER_ID }}
                
          xcrun altool --upload-app -f $RUNNER_TEMP/export/movies.ipa \
                -t ios \
                --apiKey ${{ secrets.APPSTORE_API_KEY_ID }} \
                --apiIssuer ${{ secrets.APPSTORE_ISSUER_ID }}
          
      
          
      - name: Clean up keychain and provisioning profile
        if: ${{ always() }}
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
          rm ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.mobileprovision
          rm ~/Library/MobileDevice/Provisioning\ Profiles/moviesapp_profile.mobileprovision
          rm ~/private_keys/AuthKey_${{ secrets.APPSTORE_API_KEY_ID }}.p8
